<?php
$GOOGLE_CLIENT_ID = '';
$GOOGLE_CLIENT_SECRET = '';
$GOOGLE_REDIRECT_URI = '';

define('GOOGLE_CLIENT_ID', getenv('GOOGLE_CLIENT_ID') ?: $GOOGLE_CLIENT_ID);
define('GOOGLE_CLIENT_SECRET', getenv('GOOGLE_CLIENT_SECRET') ?: $GOOGLE_CLIENT_SECRET);
define('GOOGLE_REDIRECT_URI', getenv('GOOGLE_REDIRECT_URI') ?: $GOOGLE_REDIRECT_URI);
